<?php


/**
 * Skeleton subclass for representing a row from the 'investment_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Feb 20 09:15:58 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.investment
 */
class InvestmentProduct extends BaseInvestmentProduct 
{
  /**
   * Return the rateTerm object
   * 
   * @param int $term
   * @return RateTerm 
   */
  public function getInterestRate($term)
  {
    $criteria = RateTermPeer::addTermCriteria($term);
    $criteria->addJoin(InvestmentProductInterestRatePeer::RATE_TERM_ID, RateTermPeer::ID, Criteria::LEFT_JOIN);
    $criteria->add(InvestmentProductInterestRatePeer::PRODUCT_ID, $this->getId());
    
    $productInteresRate = InvestmentProductInterestRatePeer::doSelectOne($criteria);
    
    if(!$productInteresRate){
      $productInteresRate = new InvestmentProductInterestRate();
    }
    
    return $productInteresRate->getRateTerm();
  }
  
   /**
   * Get rateTerms
    * 
   * @param Criteria $c
   * @return array object(RateTerm) 
   */
  public function getInterestRates($criteria = null) 
  {
    $rateTerms = array();
    foreach($this->getInvestmentProductInterestRatesJoinRateTerm($criteria) as $ref){
      $rateTerms[] = $ref->getRateTerm();
    }
    return $rateTerms;
  }
  
  /**
   * Method toString
   * 
   * @return string 
   */
  public function  __toString() 
  {
    return $this->getName();
  }
} // InvestmentProduct
