<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/27 03:25:00
sfConfig::add(array(
  'mod_investment_transaction_history_enabled' => true,
  'mod_investment_transaction_history_view_class' => 'sfPHP',
));
