<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/27 03:24:40
$this->security = array (
  'delete' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'new' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'cashier',
      ),
    ),
  ),
  'payment' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'cashier',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
