<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/27 03:09:12
$this->security = array (
  'delete' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
