<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/28 16:50:00
sfConfig::add(array(
  'mod_associate_account_enabled' => true,
  'mod_associate_account_view_class' => 'sfPHP',
));
