<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/27 03:12:55
sfConfig::add(array(
  'mod_associate_organization_enabled' => true,
  'mod_associate_organization_view_class' => 'sfPHP',
));
