<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/27 03:24:40
sfConfig::add(array(
  'mod_investment_expired_enabled' => true,
  'mod_investment_expired_view_class' => 'sfPHP',
));
