<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/27 03:26:49
sfConfig::add(array(
  'mod_account_transaction_enabled' => true,
  'mod_account_transaction_view_class' => 'sfPHP',
));
