<?php


/**
 * Skeleton subclass for representing a row from the 'agency' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Feb 17 18:59:53 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.basic
 */
class Agency extends BaseAgency {
  
  /**
   * Method toString
   * 
   * @return string 
   */
  public function __toString() 
  {
    return $this->getName();
  }

} // Agency
