<?php


/**
 * Skeleton subclass for representing a row from the 'configuration' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Mar 30 12:00:39 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.basic
 */
class Configuration extends BaseConfiguration 
{
  /**
   * name attribute = 'title_retport'
   */
  const TITLE_REPORT = 'title_report';
  
  /**
   * Method toString
   * 
   * @return string 
   */
  public function __toString() 
  {
    return $this->getValue();
  }
} // Configuration
