generator:
  class: sfPropelGenerator
  param:
    model_class:           Agency
    theme:                 fynance
    non_verbose_templates: true
    with_show:             false
    singular:              agency
    plural:                agencies
    route_prefix:          agency
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:  
        title: Agencies
        display: [=name]
        batch_actions: {}
        object_actions:
          _edit: ~
        actions:
          _new: {label: New}
      filter:  
        display:  [name]
      form:    ~
      edit:    
        title: Editing Agency "%%name%%"
        actions:
          _delete: {label: Delete}
          _save: {label: Save}
          _list: ~
      new:     
        actions:
          _save: {label: Save}
          _list: ~
