<?php


/**
 * This class defines the structure of the 'transaction' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 21 16:12:26 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.basic.map
 */
class TransactionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.basic.map.TransactionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('transaction');
		$this->setPhpName('Transaction');
		$this->setClassname('Transaction');
		$this->setPackage('lib.model.basic');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'BIGINT', true, null, null);
		$this->addForeignKey('CASH_ID', 'CashId', 'BIGINT', 'cash', 'ID', false, null, null);
		$this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addForeignKey('TRANSACTION_TYPE_ID', 'TransactionTypeId', 'BIGINT', 'transaction_type', 'ID', true, null, null);
		$this->addColumn('TYPE', 'Type', 'VARCHAR', true, 30, 'general');
		$this->addColumn('AMOUNT', 'Amount', 'DECIMAL', true, 18, null);
		$this->addColumn('OBSERVATION', 'Observation', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Cash', 'Cash', RelationMap::MANY_TO_ONE, array('cash_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('User', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('TransactionType', 'TransactionType', RelationMap::MANY_TO_ONE, array('transaction_type_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('AccountTransaction', 'AccountTransaction', RelationMap::ONE_TO_ONE, array('id' => 'id', ), 'CASCADE', 'RESTRICT');
    $this->addRelation('CreditTransaction', 'CreditTransaction', RelationMap::ONE_TO_ONE, array('id' => 'id', ), 'CASCADE', 'RESTRICT');
    $this->addRelation('InvestmentTransaction', 'InvestmentTransaction', RelationMap::ONE_TO_ONE, array('id' => 'id', ), 'CASCADE', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // TransactionTableMap
