<?php


/**
 * Skeleton subclass for representing a row from the 'phone' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Feb 16 06:30:49 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.associate
 */
class Phone extends BasePhone 
{
  /**
   * Save this object
   * 
   * @param PropelPDO $con 
   */
  public function save(PropelPDO $con = null) 
  {  
    if(!in_array($this->getNumber(), array(null, '', array()), true)){
      parent::save($con);
    }
  }
  
  /**
   * Method toString
   * 
   * @return string 
   */
  public function __toString() 
  {
    return $this->getNumber();
  }

} // Phone
