<?php


/**
 * Skeleton subclass for performing query and update operations on the 'credit_product_interest_rate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Aug  2 09:37:29 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.credit
 */
class CreditProductInterestRatePeer extends BaseCreditProductInterestRatePeer 
{
} // CreditProductInterestRatePeer
