<?php


/**
 * Skeleton subclass for representing a row from the 'credit_guarantee_personal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Feb 20 16:26:34 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.credit
 */
class GuaranteePersonal extends BaseGuaranteePersonal 
{
  /**
   * Method toString
   * 
   * @return string 
   */
  public function  __toString() 
  {
    return $this->getAssociate()->getName();
  }

} // CreditGuaranteePersonal
