<?php


/**
 * Skeleton subclass for performing query and update operations on the 'country' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Feb 16 06:30:49 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.location
 */
class CountryPeer extends BaseCountryPeer
{
  /**
   * Retrieve for select
   * 
   * @param string $q
   * @param int $limit
   * @return array object
   */  
  static public function retrieveForSelect($q, $limit)
  {
    $criteria = new Criteria();
    $criteria->add(self::NAME, '%'.$q.'%', Criteria::LIKE);
    $criteria->addAscendingOrderByColumn(self::NAME);
    $criteria->setLimit($limit);

    $countries = array();
    foreach (self::doSelect($criteria) as $country)
    {
      $countries[$country->getId()] = (string) $country;
    }

    return $countries;
  }
}
