generator:
  class: sfPropelGenerator
  param:
    model_class:           Cash
    theme:                 fynance
    non_verbose_templates: true
    with_show:             false
    singular:              cash
    plural:                cashs
    route_prefix:          cash
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Cash
        display: [=name, agency, balance, updated_at]
        batch_actions: {}
        object_actions:
          _edit: ~
        actions:
          _new: {label: New}
      filter:  
        display: [name, agency_id]
      form:    ~
      edit:
        title: Editing Cash "%%name%%"
        actions:
          _delete: {label: Delete}
          _save: {label: Save}
          _list: ~
      new:     
        actions:
          _save: {label: Save}
          _list: ~
