<?php


/**
 * Skeleton subclass for representing a row from the 'account_product_interest_rate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Aug  2 09:37:24 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.account
 */
class AccountProductInterestRate extends BaseAccountProductInterestRate 
{
  /**
   * 
   * @return boolean 
   */
  public function isCurrent()
  {
    $b = false;
    
    $max = AccountProductInterestRatePeer::maxByProductId($this->getProductId());
    
    if($this->getRateUniqueId() == $max){
      $b = true;
    }
    
    return $b;
  }
} // AccountProductInterestRate
