<?php


/**
 * Skeleton subclass for performing query and update operations on the 'account_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Feb 17 18:59:47 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.account
 */
class AccountProductPeer extends BaseAccountProductPeer 
{
  /**
   * Form of interest payments
   * 
   * @var array
   */
  public static $capitalization_frequency = array(
      'daily' => 'Daily',
      'monthly' => 'Monthly',
      'quarterly' => 'Quarterly',
      'biyearly' => 'Biyearly',
      'yearly' => 'Yearly',
  );
  
  /**
   * Return the last date the given month 
   * 
   * @param date $date
   * @return type 
   */
  public function lastDateMonth($date)
  {
    return $date;
  }
} // AccountProductPeer
