<?php

/**
 * Base class that represents a row from the 'transaction' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jan  8 00:50:48 2023
 *
 * @package    lib.model.basic.om
 */
abstract class BaseTransaction extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TransactionPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the cash_id field.
	 * @var        string
	 */
	protected $cash_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the transaction_type_id field.
	 * @var        string
	 */
	protected $transaction_type_id;

	/**
	 * The value for the amount field.
	 * @var        string
	 */
	protected $amount;

	/**
	 * The value for the observation field.
	 * @var        string
	 */
	protected $observation;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the credit_id field.
	 * @var        string
	 */
	protected $credit_id;

	/**
	 * The value for the account_id field.
	 * @var        string
	 */
	protected $account_id;

	/**
	 * The value for the bankbook_id field.
	 * @var        string
	 */
	protected $bankbook_id;

	/**
	 * The value for the account_balance field.
	 * @var        string
	 */
	protected $account_balance;

	/**
	 * The value for the investment_id field.
	 * @var        string
	 */
	protected $investment_id;

	/**
	 * @var        Cash
	 */
	protected $aCash;

	/**
	 * @var        sfGuardUser
	 */
	protected $aUser;

	/**
	 * @var        TransactionType
	 */
	protected $aTransactionType;

	/**
	 * @var        Credit
	 */
	protected $aCredit;

	/**
	 * @var        Account
	 */
	protected $aAccount;

	/**
	 * @var        Bankbook
	 */
	protected $aBankbook;

	/**
	 * @var        Investment
	 */
	protected $aInvestment;

	/**
	 * @var        array Payment[] Collection to store aggregation of Payment objects.
	 */
	protected $collPayments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPayments.
	 */
	private $lastPaymentCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TransactionPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [cash_id] column value.
	 * 
	 * @return     string
	 */
	public function getCashId()
	{
		return $this->cash_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [transaction_type_id] column value.
	 * 
	 * @return     string
	 */
	public function getTransactionTypeId()
	{
		return $this->transaction_type_id;
	}

	/**
	 * Get the [amount] column value.
	 * 
	 * @return     string
	 */
	public function getAmount()
	{
		return $this->amount;
	}

	/**
	 * Get the [observation] column value.
	 * 
	 * @return     string
	 */
	public function getObservation()
	{
		return $this->observation;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [credit_id] column value.
	 * 
	 * @return     string
	 */
	public function getCreditId()
	{
		return $this->credit_id;
	}

	/**
	 * Get the [account_id] column value.
	 * 
	 * @return     string
	 */
	public function getAccountId()
	{
		return $this->account_id;
	}

	/**
	 * Get the [bankbook_id] column value.
	 * 
	 * @return     string
	 */
	public function getBankbookId()
	{
		return $this->bankbook_id;
	}

	/**
	 * Get the [account_balance] column value.
	 * 
	 * @return     string
	 */
	public function getAccountBalance()
	{
		return $this->account_balance;
	}

	/**
	 * Get the [investment_id] column value.
	 * 
	 * @return     string
	 */
	public function getInvestmentId()
	{
		return $this->investment_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = TransactionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [cash_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setCashId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cash_id !== $v) {
			$this->cash_id = $v;
			$this->modifiedColumns[] = TransactionPeer::CASH_ID;
		}

		if ($this->aCash !== null && $this->aCash->getId() !== $v) {
			$this->aCash = null;
		}

		return $this;
	} // setCashId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = TransactionPeer::USER_ID;
		}

		if ($this->aUser !== null && $this->aUser->getId() !== $v) {
			$this->aUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [transaction_type_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setTransactionTypeId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->transaction_type_id !== $v) {
			$this->transaction_type_id = $v;
			$this->modifiedColumns[] = TransactionPeer::TRANSACTION_TYPE_ID;
		}

		if ($this->aTransactionType !== null && $this->aTransactionType->getId() !== $v) {
			$this->aTransactionType = null;
		}

		return $this;
	} // setTransactionTypeId()

	/**
	 * Set the value of [amount] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setAmount($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->amount !== $v) {
			$this->amount = $v;
			$this->modifiedColumns[] = TransactionPeer::AMOUNT;
		}

		return $this;
	} // setAmount()

	/**
	 * Set the value of [observation] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setObservation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->observation !== $v) {
			$this->observation = $v;
			$this->modifiedColumns[] = TransactionPeer::OBSERVATION;
		}

		return $this;
	} // setObservation()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = TransactionPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [credit_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setCreditId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->credit_id !== $v) {
			$this->credit_id = $v;
			$this->modifiedColumns[] = TransactionPeer::CREDIT_ID;
		}

		if ($this->aCredit !== null && $this->aCredit->getId() !== $v) {
			$this->aCredit = null;
		}

		return $this;
	} // setCreditId()

	/**
	 * Set the value of [account_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setAccountId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->account_id !== $v) {
			$this->account_id = $v;
			$this->modifiedColumns[] = TransactionPeer::ACCOUNT_ID;
		}

		if ($this->aAccount !== null && $this->aAccount->getId() !== $v) {
			$this->aAccount = null;
		}

		return $this;
	} // setAccountId()

	/**
	 * Set the value of [bankbook_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setBankbookId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->bankbook_id !== $v) {
			$this->bankbook_id = $v;
			$this->modifiedColumns[] = TransactionPeer::BANKBOOK_ID;
		}

		if ($this->aBankbook !== null && $this->aBankbook->getId() !== $v) {
			$this->aBankbook = null;
		}

		return $this;
	} // setBankbookId()

	/**
	 * Set the value of [account_balance] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setAccountBalance($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->account_balance !== $v) {
			$this->account_balance = $v;
			$this->modifiedColumns[] = TransactionPeer::ACCOUNT_BALANCE;
		}

		return $this;
	} // setAccountBalance()

	/**
	 * Set the value of [investment_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Transaction The current object (for fluent API support)
	 */
	public function setInvestmentId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->investment_id !== $v) {
			$this->investment_id = $v;
			$this->modifiedColumns[] = TransactionPeer::INVESTMENT_ID;
		}

		if ($this->aInvestment !== null && $this->aInvestment->getId() !== $v) {
			$this->aInvestment = null;
		}

		return $this;
	} // setInvestmentId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->cash_id = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->user_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->transaction_type_id = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->amount = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->observation = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->created_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->credit_id = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->account_id = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->bankbook_id = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->account_balance = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->investment_id = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = TransactionPeer::NUM_COLUMNS - TransactionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Transaction object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCash !== null && $this->cash_id !== $this->aCash->getId()) {
			$this->aCash = null;
		}
		if ($this->aUser !== null && $this->user_id !== $this->aUser->getId()) {
			$this->aUser = null;
		}
		if ($this->aTransactionType !== null && $this->transaction_type_id !== $this->aTransactionType->getId()) {
			$this->aTransactionType = null;
		}
		if ($this->aCredit !== null && $this->credit_id !== $this->aCredit->getId()) {
			$this->aCredit = null;
		}
		if ($this->aAccount !== null && $this->account_id !== $this->aAccount->getId()) {
			$this->aAccount = null;
		}
		if ($this->aBankbook !== null && $this->bankbook_id !== $this->aBankbook->getId()) {
			$this->aBankbook = null;
		}
		if ($this->aInvestment !== null && $this->investment_id !== $this->aInvestment->getId()) {
			$this->aInvestment = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TransactionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TransactionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCash = null;
			$this->aUser = null;
			$this->aTransactionType = null;
			$this->aCredit = null;
			$this->aAccount = null;
			$this->aBankbook = null;
			$this->aInvestment = null;
			$this->collPayments = null;
			$this->lastPaymentCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TransactionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTransaction:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				TransactionPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTransaction:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TransactionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTransaction:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(TransactionPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTransaction:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				TransactionPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCash !== null) {
				if ($this->aCash->isModified() || $this->aCash->isNew()) {
					$affectedRows += $this->aCash->save($con);
				}
				$this->setCash($this->aCash);
			}

			if ($this->aUser !== null) {
				if ($this->aUser->isModified() || $this->aUser->isNew()) {
					$affectedRows += $this->aUser->save($con);
				}
				$this->setUser($this->aUser);
			}

			if ($this->aTransactionType !== null) {
				if ($this->aTransactionType->isModified() || $this->aTransactionType->isNew()) {
					$affectedRows += $this->aTransactionType->save($con);
				}
				$this->setTransactionType($this->aTransactionType);
			}

			if ($this->aCredit !== null) {
				if ($this->aCredit->isModified() || $this->aCredit->isNew()) {
					$affectedRows += $this->aCredit->save($con);
				}
				$this->setCredit($this->aCredit);
			}

			if ($this->aAccount !== null) {
				if ($this->aAccount->isModified() || $this->aAccount->isNew()) {
					$affectedRows += $this->aAccount->save($con);
				}
				$this->setAccount($this->aAccount);
			}

			if ($this->aBankbook !== null) {
				if ($this->aBankbook->isModified() || $this->aBankbook->isNew()) {
					$affectedRows += $this->aBankbook->save($con);
				}
				$this->setBankbook($this->aBankbook);
			}

			if ($this->aInvestment !== null) {
				if ($this->aInvestment->isModified() || $this->aInvestment->isNew()) {
					$affectedRows += $this->aInvestment->save($con);
				}
				$this->setInvestment($this->aInvestment);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TransactionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TransactionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TransactionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPayments !== null) {
				foreach ($this->collPayments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCash !== null) {
				if (!$this->aCash->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCash->getValidationFailures());
				}
			}

			if ($this->aUser !== null) {
				if (!$this->aUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUser->getValidationFailures());
				}
			}

			if ($this->aTransactionType !== null) {
				if (!$this->aTransactionType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTransactionType->getValidationFailures());
				}
			}

			if ($this->aCredit !== null) {
				if (!$this->aCredit->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCredit->getValidationFailures());
				}
			}

			if ($this->aAccount !== null) {
				if (!$this->aAccount->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAccount->getValidationFailures());
				}
			}

			if ($this->aBankbook !== null) {
				if (!$this->aBankbook->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aBankbook->getValidationFailures());
				}
			}

			if ($this->aInvestment !== null) {
				if (!$this->aInvestment->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aInvestment->getValidationFailures());
				}
			}


			if (($retval = TransactionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPayments !== null) {
					foreach ($this->collPayments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TransactionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCashId();
				break;
			case 2:
				return $this->getUserId();
				break;
			case 3:
				return $this->getTransactionTypeId();
				break;
			case 4:
				return $this->getAmount();
				break;
			case 5:
				return $this->getObservation();
				break;
			case 6:
				return $this->getCreatedAt();
				break;
			case 7:
				return $this->getCreditId();
				break;
			case 8:
				return $this->getAccountId();
				break;
			case 9:
				return $this->getBankbookId();
				break;
			case 10:
				return $this->getAccountBalance();
				break;
			case 11:
				return $this->getInvestmentId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TransactionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCashId(),
			$keys[2] => $this->getUserId(),
			$keys[3] => $this->getTransactionTypeId(),
			$keys[4] => $this->getAmount(),
			$keys[5] => $this->getObservation(),
			$keys[6] => $this->getCreatedAt(),
			$keys[7] => $this->getCreditId(),
			$keys[8] => $this->getAccountId(),
			$keys[9] => $this->getBankbookId(),
			$keys[10] => $this->getAccountBalance(),
			$keys[11] => $this->getInvestmentId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TransactionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCashId($value);
				break;
			case 2:
				$this->setUserId($value);
				break;
			case 3:
				$this->setTransactionTypeId($value);
				break;
			case 4:
				$this->setAmount($value);
				break;
			case 5:
				$this->setObservation($value);
				break;
			case 6:
				$this->setCreatedAt($value);
				break;
			case 7:
				$this->setCreditId($value);
				break;
			case 8:
				$this->setAccountId($value);
				break;
			case 9:
				$this->setBankbookId($value);
				break;
			case 10:
				$this->setAccountBalance($value);
				break;
			case 11:
				$this->setInvestmentId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TransactionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCashId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUserId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTransactionTypeId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAmount($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setObservation($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCreatedAt($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCreditId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setAccountId($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setBankbookId($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setAccountBalance($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setInvestmentId($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TransactionPeer::DATABASE_NAME);

		if ($this->isColumnModified(TransactionPeer::ID)) $criteria->add(TransactionPeer::ID, $this->id);
		if ($this->isColumnModified(TransactionPeer::CASH_ID)) $criteria->add(TransactionPeer::CASH_ID, $this->cash_id);
		if ($this->isColumnModified(TransactionPeer::USER_ID)) $criteria->add(TransactionPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(TransactionPeer::TRANSACTION_TYPE_ID)) $criteria->add(TransactionPeer::TRANSACTION_TYPE_ID, $this->transaction_type_id);
		if ($this->isColumnModified(TransactionPeer::AMOUNT)) $criteria->add(TransactionPeer::AMOUNT, $this->amount);
		if ($this->isColumnModified(TransactionPeer::OBSERVATION)) $criteria->add(TransactionPeer::OBSERVATION, $this->observation);
		if ($this->isColumnModified(TransactionPeer::CREATED_AT)) $criteria->add(TransactionPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(TransactionPeer::CREDIT_ID)) $criteria->add(TransactionPeer::CREDIT_ID, $this->credit_id);
		if ($this->isColumnModified(TransactionPeer::ACCOUNT_ID)) $criteria->add(TransactionPeer::ACCOUNT_ID, $this->account_id);
		if ($this->isColumnModified(TransactionPeer::BANKBOOK_ID)) $criteria->add(TransactionPeer::BANKBOOK_ID, $this->bankbook_id);
		if ($this->isColumnModified(TransactionPeer::ACCOUNT_BALANCE)) $criteria->add(TransactionPeer::ACCOUNT_BALANCE, $this->account_balance);
		if ($this->isColumnModified(TransactionPeer::INVESTMENT_ID)) $criteria->add(TransactionPeer::INVESTMENT_ID, $this->investment_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TransactionPeer::DATABASE_NAME);

		$criteria->add(TransactionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Transaction (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCashId($this->cash_id);

		$copyObj->setUserId($this->user_id);

		$copyObj->setTransactionTypeId($this->transaction_type_id);

		$copyObj->setAmount($this->amount);

		$copyObj->setObservation($this->observation);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setCreditId($this->credit_id);

		$copyObj->setAccountId($this->account_id);

		$copyObj->setBankbookId($this->bankbook_id);

		$copyObj->setAccountBalance($this->account_balance);

		$copyObj->setInvestmentId($this->investment_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPayments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPayment($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Transaction Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TransactionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TransactionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Cash object.
	 *
	 * @param      Cash $v
	 * @return     Transaction The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCash(Cash $v = null)
	{
		if ($v === null) {
			$this->setCashId(NULL);
		} else {
			$this->setCashId($v->getId());
		}

		$this->aCash = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Cash object, it will not be re-added.
		if ($v !== null) {
			$v->addTransaction($this);
		}

		return $this;
	}


	/**
	 * Get the associated Cash object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Cash The associated Cash object.
	 * @throws     PropelException
	 */
	public function getCash(PropelPDO $con = null)
	{
		if ($this->aCash === null && (($this->cash_id !== "" && $this->cash_id !== null))) {
			$this->aCash = CashPeer::retrieveByPk($this->cash_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCash->addTransactions($this);
			 */
		}
		return $this->aCash;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Transaction The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->aUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addTransaction($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getUser(PropelPDO $con = null)
	{
		if ($this->aUser === null && ($this->user_id !== null)) {
			$this->aUser = sfGuardUserPeer::retrieveByPk($this->user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUser->addTransactions($this);
			 */
		}
		return $this->aUser;
	}

	/**
	 * Declares an association between this object and a TransactionType object.
	 *
	 * @param      TransactionType $v
	 * @return     Transaction The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTransactionType(TransactionType $v = null)
	{
		if ($v === null) {
			$this->setTransactionTypeId(NULL);
		} else {
			$this->setTransactionTypeId($v->getId());
		}

		$this->aTransactionType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TransactionType object, it will not be re-added.
		if ($v !== null) {
			$v->addTransaction($this);
		}

		return $this;
	}


	/**
	 * Get the associated TransactionType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TransactionType The associated TransactionType object.
	 * @throws     PropelException
	 */
	public function getTransactionType(PropelPDO $con = null)
	{
		if ($this->aTransactionType === null && (($this->transaction_type_id !== "" && $this->transaction_type_id !== null))) {
			$this->aTransactionType = TransactionTypePeer::retrieveByPk($this->transaction_type_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTransactionType->addTransactions($this);
			 */
		}
		return $this->aTransactionType;
	}

	/**
	 * Declares an association between this object and a Credit object.
	 *
	 * @param      Credit $v
	 * @return     Transaction The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCredit(Credit $v = null)
	{
		if ($v === null) {
			$this->setCreditId(NULL);
		} else {
			$this->setCreditId($v->getId());
		}

		$this->aCredit = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Credit object, it will not be re-added.
		if ($v !== null) {
			$v->addTransaction($this);
		}

		return $this;
	}


	/**
	 * Get the associated Credit object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Credit The associated Credit object.
	 * @throws     PropelException
	 */
	public function getCredit(PropelPDO $con = null)
	{
		if ($this->aCredit === null && (($this->credit_id !== "" && $this->credit_id !== null))) {
			$this->aCredit = CreditPeer::retrieveByPk($this->credit_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCredit->addTransactions($this);
			 */
		}
		return $this->aCredit;
	}

	/**
	 * Declares an association between this object and a Account object.
	 *
	 * @param      Account $v
	 * @return     Transaction The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAccount(Account $v = null)
	{
		if ($v === null) {
			$this->setAccountId(NULL);
		} else {
			$this->setAccountId($v->getId());
		}

		$this->aAccount = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Account object, it will not be re-added.
		if ($v !== null) {
			$v->addTransaction($this);
		}

		return $this;
	}


	/**
	 * Get the associated Account object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Account The associated Account object.
	 * @throws     PropelException
	 */
	public function getAccount(PropelPDO $con = null)
	{
		if ($this->aAccount === null && (($this->account_id !== "" && $this->account_id !== null))) {
			$this->aAccount = AccountPeer::retrieveByPk($this->account_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAccount->addTransactions($this);
			 */
		}
		return $this->aAccount;
	}

	/**
	 * Declares an association between this object and a Bankbook object.
	 *
	 * @param      Bankbook $v
	 * @return     Transaction The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setBankbook(Bankbook $v = null)
	{
		if ($v === null) {
			$this->setBankbookId(NULL);
		} else {
			$this->setBankbookId($v->getId());
		}

		$this->aBankbook = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Bankbook object, it will not be re-added.
		if ($v !== null) {
			$v->addTransaction($this);
		}

		return $this;
	}


	/**
	 * Get the associated Bankbook object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Bankbook The associated Bankbook object.
	 * @throws     PropelException
	 */
	public function getBankbook(PropelPDO $con = null)
	{
		if ($this->aBankbook === null && (($this->bankbook_id !== "" && $this->bankbook_id !== null))) {
			$this->aBankbook = BankbookPeer::retrieveByPk($this->bankbook_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aBankbook->addTransactions($this);
			 */
		}
		return $this->aBankbook;
	}

	/**
	 * Declares an association between this object and a Investment object.
	 *
	 * @param      Investment $v
	 * @return     Transaction The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setInvestment(Investment $v = null)
	{
		if ($v === null) {
			$this->setInvestmentId(NULL);
		} else {
			$this->setInvestmentId($v->getId());
		}

		$this->aInvestment = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Investment object, it will not be re-added.
		if ($v !== null) {
			$v->addTransaction($this);
		}

		return $this;
	}


	/**
	 * Get the associated Investment object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Investment The associated Investment object.
	 * @throws     PropelException
	 */
	public function getInvestment(PropelPDO $con = null)
	{
		if ($this->aInvestment === null && (($this->investment_id !== "" && $this->investment_id !== null))) {
			$this->aInvestment = InvestmentPeer::retrieveByPk($this->investment_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aInvestment->addTransactions($this);
			 */
		}
		return $this->aInvestment;
	}

	/**
	 * Clears out the collPayments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPayments()
	 */
	public function clearPayments()
	{
		$this->collPayments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPayments collection (array).
	 *
	 * By default this just sets the collPayments collection to an empty array (like clearcollPayments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPayments()
	{
		$this->collPayments = array();
	}

	/**
	 * Gets an array of Payment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Transaction has previously been saved, it will retrieve
	 * related Payments from storage. If this Transaction is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Payment[]
	 * @throws     PropelException
	 */
	public function getPayments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPayments === null) {
			if ($this->isNew()) {
			   $this->collPayments = array();
			} else {

				$criteria->add(PaymentPeer::TRANSACTION_ID, $this->id);

				PaymentPeer::addSelectColumns($criteria);
				$this->collPayments = PaymentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PaymentPeer::TRANSACTION_ID, $this->id);

				PaymentPeer::addSelectColumns($criteria);
				if (!isset($this->lastPaymentCriteria) || !$this->lastPaymentCriteria->equals($criteria)) {
					$this->collPayments = PaymentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPaymentCriteria = $criteria;
		return $this->collPayments;
	}

	/**
	 * Returns the number of related Payment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Payment objects.
	 * @throws     PropelException
	 */
	public function countPayments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPayments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PaymentPeer::TRANSACTION_ID, $this->id);

				$count = PaymentPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PaymentPeer::TRANSACTION_ID, $this->id);

				if (!isset($this->lastPaymentCriteria) || !$this->lastPaymentCriteria->equals($criteria)) {
					$count = PaymentPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPayments);
				}
			} else {
				$count = count($this->collPayments);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Payment object to this object
	 * through the Payment foreign key attribute.
	 *
	 * @param      Payment $l Payment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPayment(Payment $l)
	{
		if ($this->collPayments === null) {
			$this->initPayments();
		}
		if (!in_array($l, $this->collPayments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPayments, $l);
			$l->setTransaction($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Transaction is new, it will return
	 * an empty collection; or if this Transaction has previously
	 * been saved, it will retrieve related Payments from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Transaction.
	 */
	public function getPaymentsJoinCredit($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TransactionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPayments === null) {
			if ($this->isNew()) {
				$this->collPayments = array();
			} else {

				$criteria->add(PaymentPeer::TRANSACTION_ID, $this->id);

				$this->collPayments = PaymentPeer::doSelectJoinCredit($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PaymentPeer::TRANSACTION_ID, $this->id);

			if (!isset($this->lastPaymentCriteria) || !$this->lastPaymentCriteria->equals($criteria)) {
				$this->collPayments = PaymentPeer::doSelectJoinCredit($criteria, $con, $join_behavior);
			}
		}
		$this->lastPaymentCriteria = $criteria;

		return $this->collPayments;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPayments) {
				foreach ((array) $this->collPayments as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPayments = null;
			$this->aCash = null;
			$this->aUser = null;
			$this->aTransactionType = null;
			$this->aCredit = null;
			$this->aAccount = null;
			$this->aBankbook = null;
			$this->aInvestment = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTransaction:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTransaction::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTransaction
