generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 fynance
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_propel_route:     1

    config:
      fields:
        password_again: { label: "Password (again)" }

      list:
        title:   Users
        display: [=username, created_at, last_login]
        batch_actions: {}
        actions:
          _new: {label: New}
        object_actions:
          _edit: ~

      form:
        class: UserAdminForm
        display:
          "NONE":                   [username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, sf_guard_user_group_list, sf_guard_user_permission_list]

      edit:
        title: Editing User "%%username%%"
        actions:
          _delete: {label: Delete}
          _save: {label: Save}
          _list: ~

      new:
        title: New User
        actions:
          _save: {label: Save}
          _list: ~
